---
title: "Figure sizing"
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment=NA,message=FALSE,
                      warning=FALSE,
                      fig.with=6,fig.asp=0.618,
                      out.width="70%",fig.align="center")
```

## One figure

```{r one fig, fig.cap="Figure 1.bula bula"}
library(tidyverse)

ggplot(mpg, mapping = aes(displ, hwy)) +
  geom_point() +
  geom_smooth() 

```

## Two figures

```{r two figs,out.width="50%",fig.align="default",fig.show='hold',fig.cap="Figure 2.bula bula"}
suv <- mpg %>% filter(class == "suv")
compact <- mpg %>% filter(class == "compact")

x_scale <- scale_x_continuous(limits = range(mpg$displ))
y_scale <- scale_y_continuous(limits = range(mpg$hwy))
col_scale <- scale_colour_discrete(limits = unique(mpg$drv))

ggplot(suv, aes(displ, hwy, colour = drv)) +
  geom_point() +
  x_scale +
  y_scale +
  col_scale

ggplot(compact, aes(displ, hwy, colour = drv)) +
  geom_point() +
  x_scale +
  y_scale +
  col_scale
```


